version: "3.9"
services:
  balancer:
    image: "balancer-demo"
    ports:
      - "5000:80"
    links:
      - "server-a:server-a"
      - "server-b:server-b"
      - "server-c:server-c"
  server-a:
    image: "httpd"
    volumes:
      - type: bind
        source: html/a
        target: /usr/local/apache2/htdocs/
        read_only: True
  server-b:
    image: "httpd"
    volumes:
      - type: bind
        source: html/b
        target: /usr/local/apache2/htdocs/
        read_only: True
  server-c:
    image: "httpd"
    volumes:
      - type: bind
        source: html/c
        target: /usr/local/apache2/htdocs/
        read_only: True
